// ============================================================================
// MediKiosk — Standalone / Vercel Instant Demo Fallback Data Layer
// Allows the entire platform (Doctor, Nurse, Kiosk, Triage, AYUSH, Admin)
// to function seamlessly on Vercel even when backend server is offline.
// ============================================================================

export const DEMO_TIMELINES: Record<string, any[]> = {
  default: [
    {
      visitId: 'vis-prev-01',
      date: new Date(Date.now() - 14 * 86400000).toISOString(),
      chiefComplaint: 'Hypertension & Bilateral Morning Headache',
      department: 'General Medicine OPD',
      departmentCode: 'GEN',
      status: 'COMPLETED',
      priority: 'NORMAL',
      doctor: {
        name: 'Dr. Yogesh Sharma',
        specialization: 'Internal Medicine & Cardiology',
        diagnosis: 'Essential Hypertension (Stage 1) with Tension Headache',
        clinicalNotes: 'Blood pressure elevated at 142/90 mmHg. Patient advised low-sodium diet and lifestyle modification.',
        treatmentPlan: 'Tab Amlodipine 5mg once daily morning after breakfast.',
      },
      aiSummary: {
        chiefComplaint: 'Throbbing morning headache and mild dizziness for 1 week',
        historyOfPresentIllness: 'Patient reported awakening with bilateral temporal headache. No visual aura, no nausea.',
        lifestyle: 'Sleep: 5.5 hours, high work stress, sedentary office desk job.',
      },
      vitals: { bpSystolic: 142, bpDiastolic: 90, pulse: 82, spo2: 98, temperature: 98.6 },
      prescriptions: [
        { medicineName: 'Tab Amlodipine', dosage: '5mg', frequency: 'Once daily (OD)', duration: '30 days' },
        { medicineName: 'Tab Paracetamol', dosage: '650mg', frequency: 'SOS (as needed)', duration: '3 days' },
      ],
      lastPrescription: 'Tab Amlodipine 5mg (OD), Tab Paracetamol 650mg (SOS)',
    },
    {
      visitId: 'vis-prev-02',
      date: new Date(Date.now() - 60 * 86400000).toISOString(),
      chiefComplaint: 'Chronic Acidity, Gastric Reflux & Sleep Interruption',
      department: 'AYUSH & Integrative Medicine',
      departmentCode: 'AYUSH',
      status: 'COMPLETED',
      priority: 'NORMAL',
      doctor: {
        name: 'Dr. Snehal Shah',
        specialization: 'Classical Homeopathy & AYUSH',
        diagnosis: 'Psora Diathesis with Pitta Prakriti Gastritis',
        clinicalNotes: 'Case totality points to Lycopodium 30C constitutional similimum. Modalities: Worse from cold food, better after warm drinks.',
        treatmentPlan: 'Lycopodium 30C single dose weekly.',
      },
      aiSummary: {
        chiefComplaint: 'Burning epigastric pain and sour regurgitation after late meals',
        historyOfPresentIllness: 'Acid reflux especially at night. Irregular food timings.',
        lifestyle: 'Late dinner habit, high tea/coffee consumption (4 cups/day).',
      },
      vitals: { bpSystolic: 128, bpDiastolic: 82, pulse: 76, spo2: 99, temperature: 98.4 },
      prescriptions: [
        { medicineName: 'Lycopodium 30C', dosage: '4 pills', frequency: 'Weekly once', duration: '4 weeks' },
      ],
      lastPrescription: 'Lycopodium 30C (4 pills weekly)',
    },
  ],
};

export const DEMO_USERS: Record<string, any> = {
  'dosanirudra@gmail.com': {
    id: 'd60eedf9-67d1-4b90-b67d-bb355f50be67',
    email: 'dosanirudra@gmail.com',
    name: 'Dosani Rudra',
    role: 'PATIENT',
    phone: '9876549999',
    patient: {
      id: '970a3d4f-c4ef-455c-b263-7f1527e0a321',
      mrn: 'MK-600754',
      name: 'Dosani Rudra',
      age: 24,
      gender: 'MALE',
      phone: '9876549999',
      medicalHistory: 'Hypertension Follow-Up & Acidity',
      visits: [
        {
          id: 'vis-rudra-01',
          token: 'P-109',
          status: 'READY_FOR_DOCTOR',
          priority: 'NORMAL',
          department: { id: 'dept-gen', name: 'General Medicine' },
          doctor: { user: { name: 'Dr. Yogesh Sharma' } },
          createdAt: new Date().toISOString(),
          reasonForVisit: 'General OPD Follow-up & Vitals',
          vitals: [{ systolic: 138, diastolic: 88, pulse: 78, temperature: 98.4, spo2: 99 }],
          summary: {
            chiefComplaint: 'Hypertension follow-up and morning throbbing headache',
            historyOfPresentIllness: 'Patient reports persistent headache in the morning. Takes Tab Amlodipine 5mg.',
            lifestyle: 'Sleep: 6 hrs, work stress, regular physical activity.',
          },
        },
      ],
    },
  },
  'doctor@demo.com': {
    id: 'doc-001',
    email: 'doctor@demo.com',
    name: 'Dr. Yogesh Sharma',
    role: 'DOCTOR',
    phone: '9876543211',
    doctorProfile: {
      id: 'doc-prof-001',
      specialization: 'General Medicine',
      qualifications: 'MBBS, MD (Medicine)',
      department: { id: 'dept-gen', name: 'General Medicine', code: 'GEN' },
    },
  },
  'nurse@demo.com': {
    id: 'nurse-001',
    email: 'nurse@demo.com',
    name: 'Preeti Patel (Nurse)',
    role: 'NURSE',
    phone: '9876543213',
    nurseProfile: {
      id: 'nurse-prof-001',
      shiftTiming: 'Morning (8 AM - 4 PM)',
      department: { id: 'dept-gen', name: 'General Medicine', code: 'GEN' },
      assignedDoctor: { id: 'doc-prof-001', user: { name: 'Dr. Yogesh Sharma' } },
    },
  },
  'triage@demo.com': {
    id: 'triage-001',
    email: 'triage@demo.com',
    name: 'Rajesh Kumar',
    role: 'TRIAGE_STAFF',
    phone: '9876543214',
  },
  'ayush@demo.com': {
    id: 'ayush-001',
    email: 'ayush@demo.com',
    name: 'Vaidya Harish Bhatt',
    role: 'AYUSH_DOCTOR',
    phone: '9876543212',
    doctorProfile: {
      id: 'ayush-prof-001',
      specialization: 'Ayurveda & Integrative Medicine',
      qualifications: 'BAMS, MD (Ayurveda)',
      department: { id: 'dept-ayush', name: 'AYUSH & Integrative Medicine', code: 'AYUSH' },
    },
  },
  'snehal.shah@demo.com': {
    id: 'ayush-002',
    email: 'snehal.shah@demo.com',
    name: 'Dr. Snehal Shah',
    role: 'AYUSH_DOCTOR',
    phone: '9876543224',
    doctorProfile: {
      id: 'ayush-prof-002',
      specialization: 'Classical Homeopathy',
      qualifications: 'BHMS, MD (Homeopathy)',
      department: { id: 'dept-ayush', name: 'AYUSH & Integrative Medicine', code: 'AYUSH' },
    },
  },
  'admin@demo.com': {
    id: 'admin-001',
    email: 'admin@demo.com',
    name: 'Amit Verma',
    role: 'HOSPITAL_ADMIN',
    phone: '9876543216',
  },
  'patient@demo.com': {
    id: 'pat-user-001',
    email: 'patient@demo.com',
    name: 'Rahul Sharma',
    role: 'PATIENT',
    phone: '9876543210',
    patient: {
      id: 'pat-001',
      mrn: 'MK-1001',
      name: 'Rahul Sharma',
      age: 28,
      gender: 'MALE',
      phone: '9876543210',
      bloodGroup: 'B+',
      abhaId: '91-8822-1923-0019',
      medicalHistory: 'Hypertension, Morning throbbing headache',
      allergies: [{ id: 'alg-1', allergen: 'Penicillin', severity: 'HIGH' }],
      medications: [{ id: 'med-1', name: 'Tab Amlodipine 5mg OD', dosage: '5mg', frequency: 'Once daily' }],
      visits: [
        {
          id: 'vis-001',
          token: 'G-101',
          status: 'READY_FOR_DOCTOR',
          priority: 'NORMAL',
          department: { id: 'dept-gen', name: 'General Medicine' },
          doctor: { user: { name: 'Dr. Yogesh Sharma' } },
          createdAt: new Date().toISOString(),
          reasonForVisit: 'Hypertension & Morning Throbbing Headache',
          queueEntry: { tokenNumber: 'G-101', priority: 'NORMAL', status: 'WAITING' },
          vitals: [{ systolic: 138, diastolic: 88, pulse: 78, temperature: 98.4, spo2: 99, recordedAt: new Date().toISOString() }],
          summary: {
            chiefComplaint: 'Morning throbbing headache and mild dizziness for 5 days',
            historyOfPresentIllness: 'Patient reports persistent bilateral throbbing headache on waking for the past 5 days. Blood pressure elevated (138/88 mmHg). Takes Tab Amlodipine 5mg daily.',
            lifestyle: 'Sleep: 6 hrs/night, High work stress, Moderate caffeine intake',
            pastMedicalHistory: 'Hypertension diagnosed 2 years ago',
            medications: 'Tab Amlodipine 5mg OD',
            allergies: 'Penicillin (Skin rash)',
          },
        },
      ],
    },
  },
};

export const DEMO_QUEUE = [
  {
    id: 'q-1',
    tokenNumber: 'G-101',
    priority: 'NORMAL',
    status: 'WAITING',
    arrivedAt: new Date(Date.now() - 15 * 60000).toISOString(),
    department: { name: 'General Medicine', code: 'GEN' },
    visit: {
      id: 'vis-001',
      token: 'G-101',
      priority: 'NORMAL',
      status: 'READY_FOR_DOCTOR',
      patient: { id: 'pat-001', name: 'Rahul Sharma', mrn: 'MK-1001', age: 28, gender: 'MALE', phone: '9876543210' },
      doctor: { user: { name: 'Dr. Yogesh Sharma' }, specialization: 'General & Internal Medicine' },
      vitals: [{ systolic: 138, diastolic: 88, pulse: 78, temperature: 98.4, spo2: 99 }],
      summary: {
        chiefComplaint: 'Morning throbbing headache & BP follow-up',
        historyOfPresentIllness: 'Patient reported waking with throbbing headaches for 5 days. Daily Amlodipine adherence.',
        lifestyle: 'Sleep: 6 hrs, work stress, moderate coffee consumption.',
      },
    },
  },
  {
    id: 'q-2',
    tokenNumber: 'O-202',
    priority: 'URGENT',
    status: 'WAITING',
    arrivedAt: new Date(Date.now() - 35 * 60000).toISOString(),
    department: { name: 'Orthopedics', code: 'ORTHO' },
    visit: {
      id: 'vis-002',
      token: 'O-202',
      priority: 'URGENT',
      status: 'IN_INTAKE',
      patient: { id: 'pat-002', name: 'Meera Patel', mrn: 'MK-1002', age: 45, gender: 'FEMALE', phone: '9876541122' },
      doctor: { user: { name: 'Dr. Vikram Seth' }, specialization: 'Orthopedics & Joint Surgery' },
      vitals: [{ systolic: 120, diastolic: 80, pulse: 82, temperature: 98.6, spo2: 98 }],
      summary: {
        chiefComplaint: 'Severe right knee joint pain & morning stiffness',
        historyOfPresentIllness: 'Difficulty climbing stairs and joint stiffness lasting 45 mins every morning.',
        lifestyle: 'Standing job, knee strain, regular walking routine.',
      },
    },
  },
  {
    id: 'q-3',
    tokenNumber: 'A-301',
    priority: 'NORMAL',
    status: 'CALLED',
    arrivedAt: new Date(Date.now() - 50 * 60000).toISOString(),
    department: { name: 'AYUSH & Integrative Medicine', code: 'AYUSH' },
    visit: {
      id: 'vis-003',
      token: 'A-301',
      priority: 'NORMAL',
      status: 'IN_CONSULTATION',
      patient: { id: 'pat-003', name: 'Sanjay Trivedi', mrn: 'MK-1003', age: 52, gender: 'MALE', phone: '9876543344' },
      doctor: { user: { name: 'Dr. Snehal Shah' }, specialization: 'Classical Homeopathy & AYUSH' },
      vitals: [{ systolic: 130, diastolic: 84, pulse: 74, temperature: 98.2, spo2: 99 }],
      summary: {
        chiefComplaint: 'Chronic acidity, indigestion and Pitta imbalance',
        historyOfPresentIllness: 'Heartburn after spicy meals, irregular meal timings, bloating in evening.',
        lifestyle: 'Late dinner habit, desk job, heavy tea intake.',
      },
    },
  },
];

export const DEMO_DOCTORS = [
  { id: 'doc-prof-001', user: { id: 'doc-001', name: 'Dr. Yogesh Sharma', email: 'doctor@demo.com' }, specialization: 'General Medicine', qualifications: 'MBBS, MD', department: { name: 'General Medicine' } },
  { id: 'doc-prof-002', user: { id: 'doc-002', name: 'Dr. Vikram Seth', email: 'vikram.seth@demo.com' }, specialization: 'Orthopedics & Joint Surgery', qualifications: 'MBBS, MS (Ortho)', department: { name: 'Orthopedics' } },
  { id: 'doc-prof-003', user: { id: 'doc-003', name: 'Vaidya Harish Bhatt', email: 'ayush@demo.com' }, specialization: 'AYUSH / Ayurveda', qualifications: 'BAMS, MD (Ayu)', department: { name: 'AYUSH & Integrative Medicine' } },
  { id: 'doc-prof-004', user: { id: 'doc-004', name: 'Dr. Snehal Shah', email: 'snehal.shah@demo.com' }, specialization: 'Homeopathy', qualifications: 'BHMS, MD (Hom)', department: { name: 'AYUSH & Integrative Medicine' } },
];
